[package]
name = "severus"
version = "0.1.0"
license = "GPL-3.0"
edition = "2018"
exclude = ["index.node"]

[lib]
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1"
tokio = { version = "1.26", features = ["macros", "rt-multi-thread"] }
serenity = { default-features = false, features = [
  "client",
  "gateway",
  "model",
  "rustls_backend",
], version = "0.11.5" }

[dependencies.neon]
version = "0.10"
default-features = false
features = ["channel-api", "napi-6", "promise-api"]
