[package]
name = "severus"
version = "0.1.0"
license = "GPL-3.0"
edition = "2018"
exclude = ["index.node"]

[lib]
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1"
webrtc = "0.7.1"
anyhow = "1.0"
serde_json = "1.0"
twilight-model = "0.12"
twilight-standby = "0.12"
tracing = "0.1"
futures = "0.3"
symphonia-core = "0.5"
byteorder = "1"
rtp = "0.6.7"
bytes = "1"
rand = "0.8.5"
log = "0.4.17"
st3 = "0.4.1"
bus = "2.3.0"

[dependencies.twilight-http]
version = "0.12"
default-features = false
features = ["native"]

[dependencies.twilight-gateway]
version = "0.12"
default-features = false
features = ["native"]

[dependencies.neon]
version = "0.10"
default-features = false
features = ["channel-api", "napi-6", "promise-api"]

[dependencies.songbird]
default-features = false
git = 'https://github.com/owlbear-rodeo/songbird.git'
branch = "streaming"
version = "0.3.2"
features = ["driver", "twilight-native", "zlib-stock"]

[dependencies.tokio]
version = "1.26"
features = ["macros", "rt-multi-thread"]

[dependencies.async-trait]
version = "0.1"

[dependencies.flume]
version = "0.10"

[dependencies.discortp]
features = ["discord-full"]
version = "0.4"

[dependencies.xsalsa20poly1305]
version = "0.9"
features = ["std"]

