[package]
name = "severus"
version = "0.1.0"
license = "GPL-3.0"
edition = "2018"
exclude = ["index.node"]

[lib]
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1"
webrtc = "0.7.1"
anyhow = "1.0"
serde_json = "1.0"
twilight-gateway = "0.12"
twilight-http = "0.12"
twilight-model = "0.12"
twilight-standby = "0.12"
tracing = "0.1"
futures = "0.3"

[dependencies.neon]
version = "0.10"
default-features = false
features = ["channel-api", "napi-6", "promise-api"]

[dependencies.songbird]
default-features = false
git = 'https://github.com/owlbear-rodeo/songbird.git'
version = "0.3.2"
features = ["driver", "twilight-rustls", "zlib-stock"]

[dependencies.tokio]
version = "1.26"
features = ["macros", "rt-multi-thread"]
